[2023-06-08 15:57:27,203][whylogs.api.writer.whylabs][INFO] - checking: https://whylabs-public.s3.us-west-2.amazonaws.com/whylogs_config/whylabs_condition_count_disabled
[2023-06-08 15:57:29,164][whylogs.api.writer.whylabs][INFO] - checking: https://whylabs-public.s3.us-west-2.amazonaws.com/whylogs_config/whylabs_condition_count_disabled
[2023-06-08 15:57:29,165][whylogs.api.writer.whylabs][INFO] - headers are: {'x-amz-id-2': 'aBcxgnoDwvO6vY38IEOYg2fHlopsp7ZVef98KgMc4+C4SeYX1vm6nwGcGwDd9NIYOSX4Z8lviQY=', 'x-amz-request-id': 'EE1NETF5D2581PWT', 'Date': 'Thu, 08 Jun 2023 22:57:31 GMT', 'Last-Modified': 'Thu, 23 Feb 2023 17:53:29 GMT', 'ETag': '"c4ca4238a0b923820dcc509a6f75849b"', 'x-amz-server-side-encryption': 'AES256', 'Accept-Ranges': 'bytes', 'Content-Type': 'binary/octet-stream', 'Server': 'AmazonS3', 'Content-Length': '1'} code: 200
[2023-06-08 15:57:29,167][whylogs.api.writer.whylabs][INFO] - found the whylabs condition count disabled file so running uncompound on condition count metrics
[2023-06-08 15:57:29,396][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A704EE9910>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /v0/organizations/org-YNx5UG/log/async/model-3
[2023-06-08 15:57:29,399][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A704EE9A90>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /v0/organizations/org-YNx5UG/log/async/model-3
[2023-06-08 15:57:29,404][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A704EE9C10>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /v0/organizations/org-YNx5UG/log/async/model-3
